### ISSUE TITLE
Possible to use "Dynamic" callback URL?

### ISSUE THREAD

**Issue by Svarto** [pusher/oauth2_proxy#12]
Thanks so much for taking over the maintenance of the oauth2_proxy repository.

I am a beginner and have a (perhaps) stupid question - is it possible to have the one oauth2_proxy instance authenticate a domain with several web services (e.g. app1.example.com, app2.example.com)? Or would I need one oauth2_proxy per webservice?

I would prefer to use a self hosted Gitlab instance as oauth2 provider, however looking at when I add a service I need to specify a specific callback URL - I can't figure out of to make this dependent on the original requested URL. For example, I go to app1.example.com, redirectes to oauth2_proxy/Gitlab login, after successful login I'm served with the requested app1.example.com login. In case I would have requested app2.example.com, then that would have been the served URL after successful login etc.

**Comment by JoelSpeed** [comment]
Hi @Svarto, your scenario is very similar to ours and can be done once #15 has been merged.

If you set up Nginx (in front of each of your services) in `auth-request` mode to verify to your single OAuth2 Proxy and set the `rd` query parameter in your sign-in url (something like `https://auth.example.com/oauth2/start?rd=https://app2.example.com`), you should then be able to protect multiple sites with a single OAuth2 Proxy

**Comment by elsesiy** [comment]
Hi @JoelSpeed,

I'm facing the same issue and have been trying to get the described setup working but the redirect to the downstream ingress doesn't work. Do you have some more documentation on how this exactly should look like?

Here's what I did:

1. Install the chart
```
helm install stable/oauth2-proxy --name login-oauth2-proxy \
    --namespace xyz \
    --set config.clientID="clientId" \
    --set config.clientSecret="clientSecret" \
    --set config.cookieSecret="cookieSecret" \
    --set extraArgs.provider="azure" \
    --set extraArgs.azure-tenant="tenantId" \
    --set extraArgs.whitelist-domain=".mydomain.com" \
    --tls
```

2. Create the ingress for oauth2_proxy:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: login-ingress-oauth2
  namespace: xyz
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: login.mydomain.com
    http:
      paths:
      - backend:
          serviceName: login-oauth2-proxy
          servicePort: 80
        path: /oauth2
  tls:
  - hosts:
    - login.mydomain.com
```

By now browsing `https://login.mydomain.com/oauth2/sign_in` works as expected.

3. Configure downstream ingress to use the oauth2_proxy:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myservice-ingress
  namespace: xyz
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-url: "https://login.mydomain.com/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://login.mydomain.com/oauth2/start?rd=service.cdhamap.com"
spec:
  rules:
  - host: service.cdhamap.com
    http:
      paths:
      - backend:
          serviceName: service-backend
          servicePort: 1337
        path: /
  tls:
  - hosts:
    - service.cdhamap.com
```

Browsing `https://service.mydomain.com` now correctly redirects me to the Microsoft Login but still shows `https://login.mydomain.com/oauth2/callback` as the redirect_uri which then after successful authentication falls back to `default-backend`.

What am I missing?

Thanks a lot!!
