### ISSUE TITLE
Receive auth token to call other Azure APIs

### ISSUE THREAD

**Issue by josemore** [pusher/oauth2_proxy#131]
## Expected Behavior
Our understanding from documentation is that it's feasible to get the OAuth / OIDC token after authentication is performed. We are currently unable to see X-Forwarded-Access-Token / Authorization headers.

Our use case: 
We have web apps requiring Azure AD authentication and we want to personalize some content based on user profile (e.g. AD groups, etc).

## Current Behaviour
Apps are running on kubernetes with hosted NGINX Ingress controllers ([external oauth config](https://kubernetes.github.io/ingress-nginx/examples/auth/oauth-external-auth/)).

OAuth proxy is deployed via stable/oauth2-proxy image in a helm chart.

Authentication works as expected (users are redirected to Azure login and oauth cookie is set).

We are not 100% sure how to obtain the token given the oauth flow is triggered from the NGINX Controller. 
We have enabled the expected config items as described in the documentation: pass_basic_auth, pass_access_token, etc.

OAuth_Proxy2 config section in chart .yaml:
```configFile: |-
    email_domains = [ "*" ]
    upstreams = [ "(app_url)" ]
    provider = "azure"
    azure_tenant = "(my_tenant)"
    pass_basic_auth = true
    pass_access_token = true
    pass_user_headers = true
    pass_host_header = true
    set_xauthrequest = true
    pass_authorization_header = true
    set_authorization_header = true
```
Ingress config:
```
ingress:
  enabled: true
  annotations:
    kubernetes.io/tls-acme: 'true'
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-response-headers: X-Auth-Request-Access-Token, Authorization
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$request_uri"
```

Can you help us confirm our use case is viable with oauth2_proxy?
Should the token be available only via HTTP headers and can it also be obtained from the cookie somehow?

Thanks

- Version used: latest
