### ISSUE TITLE
Set vs Pass Authorization Header

### ISSUE THREAD

**Issue by ap1969** [pusher/oauth2_proxy#143]
Hi all,
Sorry, this might be me being dumb (it almost certainly is), but what's the difference between the -set-authorization-header and -pass-authorization-header options?

Many thanks in advance,
Andy

**Comment by JoelSpeed** [comment]
Hey @ap1969, for clarification, see below:

`set-authorization-header` means that the `Authorization` header is set on the response to the user. This is useful for using in the Nginx Auth Request mode.

`pass-authorization-header` means the the `Authorization` header is set on requests proxied to the upstream service.

This difference between `set` and `pass` is common to the other flags around setting headers as well

Please close this issue if this has answered you question, thanks!

**Comment by m-wcislo** [comment]
Hi @JoelSpeed, 
I'm trying to use oauth2_proxy with kubernetes ingress as described in https://github.com/kubernetes/ingress-nginx/tree/master/docs/examples/auth/oauth-external-auth which from what I understand is Nginx Auth Request mode. In general everything works fine, but I cannot make auth-user/email headers to be passed to upstream - even when setting set-authorization-header or set-xauthrequest.

Do I understand correctly that those headers should be then passed in 20X or 40X response towards nginx and then nginx/ingress should somehow pass them to upstream? I checked nginx.ingress.kubernetes.io/auth-response-headers annotation but seems it is not helping either.

Could you give some hints what was your scenario/setup when adding this functionality?

Thanks in advance for your time.

**Comment by JoelSpeed** [comment]
Hey @m-wcislo, could you try authenticating to the proxy and then visiting `http(s)://yourdomain.com/oauth2/auth` and inspecting the response headers? This is the request that Nginx will make so if the headers are set on that response, we can narrow the issue to Nginx's side.

You should, with `-set-xauthrequest` see `X-Auth-Request-User` and `X-Auth-Request-Email` headers in the response. You should than, as you say, use the annotation on your Ingress object as below:
```
nginx.ingress.kubernetes.io/auth-response-headers: "X-Auth-Request-User, X-Auth-Request-Email"
``` 

Let me know which headers you see on the response from `oauth2/auth` and we can go from there debugging this

**Comment by m-wcislo** [comment]
Long story short:
Works as expected. I was changing ingress with `kubectl apply` but only after I did delete then apply the annotations were applied.

Some hints for configuring this functionality:
Annotations that supports **set-xauthrequest** and **set-authorization-header**:
```
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$request_uri"
    nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-email, authorization"
```

In nginx.conf on your ingress you should see following:
```
auth_request_set $authHeader0 $upstream_http_x_auth_request_user;
proxy_set_header 'x-auth-request-user' $authHeader0;
auth_request_set $authHeader1 $upstream_http_x_auth_request_email;
proxy_set_header 'x-auth-request-email' $authHeader1;
auth_request_set $authHeader2 $upstream_http_authorization;
proxy_set_header 'authorization' $authHeader2;
```

Also just after enabling **set-xauthrequest** and **set-authorization-header** I was getting 502 from ingress due to too big header, solution is to increase **proxy-buffer-size** to sth like 128k.

@JoelSpeed thanks a lot for quick and valuable help, and the feature itself.

**Comment by frco9** [comment]
@m-wcislo I have a similar issue, can you explain a bit more the following 
> In nginx.conf on your ingress you should see following:

I don't have a `nginx.conf` file just a configmap and I can't set the `auth_request_set`. I've tried to use the `nginx.ingress.kubernetes.io/configuration-snippet` annotation but it does not seem to work. 

Any idea ?

**Comment by JoelSpeed** [comment]
@frco9 Try these annotations the @m-wcislo suggested:

```
 annotations:
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$request_uri"
    nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-email, authorization"
```

That will generate for you the snippet in `nginx.conf`, you don't need to add it manually
