### ISSUE TITLE
Set Authorization Header not adding in response

### ISSUE THREAD

**Issue by Miouge1** [pusher/oauth2_proxy#189]
## Expected Behavior

I've set `--set-authorization-header=true` therefore I am expecting to the an `Authorization` header on the oauth2_proxy responses.

## Current Behavior

The following headers are part of the response:
```
content-length: 0
date: Mon, 17 Jun 2019 08:58:31 GMT
status: 202
strict-transport-security: max-age=15724800; includeSubDomains
```

## Context

I'm trying to follow @JoelSpeed 's article on [Kube Dashboard SSO with oauth2_proxy](https://thenewstack.io/single-sign-on-for-kubernetes-dashboard-experience/).

## Your Environment

- Version used: v3.1.0
Installed with Helm Chart stable/oauth2-proxy version v0.9.1

Oauth2_proxy args:
```
    spec:
      containers:
      - args:
        - --cookie-domain=example.com
        - --email-domain=*
        - --http-address=0.0.0.0:4180
        - --skip-provider-button
        - --upstream=file:///dev/null
        - --whitelist-domain=.example.com
        - --config=/etc/oauth2_proxy/oauth2_proxy.cfg
        - --set-authorization-header=true
```
