### ISSUE TITLE
oauth2-proxy with our Dex IDP

### ISSUE THREAD

**Issue by daroga0002** [pusher/oauth2_proxy#255]
We are integrating oauth2-proxy with our Dex IDP fro Kubernetes Dashboard.
Configuration is basing on:
- nginx ingress
- oauth2-proxy
- DeX IDP
- Kubernetes Dashboard

In general Kubernetes dashboard allows login using [Authorization (Baerer token)](https://github.com/kubernetes/dashboard/wiki/Access-control#authorization-header) so we want to use nginx ingress with auth annotations.

We setup everything running, but seems we have diffrences between JWT token which we are getting from oauth2-proxy and JWT token from kubelogin payload.

From kubelogin:
{
  "iss": "https://dex.abc.services",
  "sub": "ChFkYXdpZC5yb2dhY3pld3NraRICYWQ",
  "aud": "abc.services",
  "exp": 1566896496,
  "iat": 1566810096,
  "nonce": "272b4f908e972cc5",
  "at_hash": "KisaX68Reyuwvu2AcylUOg",
  "email": "***************",
  "email_verified": true,
  "groups": [
    "Engineering",
    "SSLVPNUsers",
    "aws_allow_logon",
    "aws_allow_sudo",
    "kohactive-vpn",
    "nexus-admin",
    "nexus-anonymous",
    "k8s_platform"
  ],
  "name": "john.kowalski"
}

Oauth2-proxy:
{
  "iss": "https://dex.abc.services",
  "sub": "ChFkYXdpZC5yb2dhY3pld3NraRICYWQ",
  "aud": "abc.services",
  "exp": 1566896496,
  "iat": 1566810096,
  "nonce": "272b4f908e972cc5",
  "at_hash": "KisaX68Reyuwvu2AcylUOg",
  "email": "***************",
  "email_verified": true,
  "name": "john.kowalski"
}

Are there any parameters to gather those data from DEX?

## Expected Behavior

Tokens should be same

## Current Behavior

Tokens are different

## Context

We are not able to integrate proper authorization for kubernetes dashboard

## Your Environment

Kubernetes 1.9

- Version used:
4.0

**Comment by daroga0002** [comment]
This seems be related to https://github.com/dexidp/dex/blob/0db538a4bbf4fc059d5bd29f0c84eee6b50a40c4/Documentation/custom-scopes-claims-clients.md question does oauth2-proxy supports such scopes?

**Comment by daroga0002** [comment]
we solved this using following configuration in oauth chart:
```
oauth2-proxy:
  config:
    clientID: 'production.something.services'
    clientSecret: '**************'
    cookieSecret: 'CdZulwsl18VvCA7G0kZaSw=='

  extraArgs: 
    cookie-secure: false
    provider: oidc
    oidc-issuer-url: https://dex.production.something.services
    set-authorization-header: true
    whitelist-domain: ".production.something.services"
    cookie-domain: ".production.something.services"
    scope: "openid groups profile"
    exclude-logging-paths: "/ping"

  service:
    type: ClusterIP

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx-internal
    hosts:
      - dashboard.production.something.services
    path: /oauth2
      
  image:
    repository: "quay.io/pusher/oauth2_proxy"
    tag: "v4.0.0"
    pullPolicy: "IfNotPresent"
```
