### ISSUE TITLE
Proxy works locally on my machine but not in kubernetes with seemingly the same config.

### ISSUE THREAD

**Issue by richtera** [pusher/oauth2_proxy#283]
For some reason I can run the proxy locally on my machine, but in kubernetes when deployed I get an error saying that there is no id_token in the response. It seems to happen in the code callback, but since the error is not written to the log I am at a loss of figuring out how to fix it.

## Expected Behavior

Oauth proxy with same settings should work locally and deployed in kubernetes.

## Current Behavior

It works fine locally. My config file is

```
provider = "oidc"
oidc_issuer_url = "https://***/"
login_url = "https://***/"
upstreams = [
    "http://localhost:7999"
]
email_domains = [
    "*"
]
client_id = "***"
client_secret = "***"
cookie_secret = "***"
skip_provider_button = true
http_address = "127.0.0.1:8000"
cookie_secure = false
scope = "openid email profile"
extra_jwt_issuers = [
	"https://***/=https://***/v1/api",
	"https://***/=https://***/v1/api"
]
silence_ping_logging = false
```
 With this setup locally I can correctly login and get to my site (I have tried to set the upstream to file:///dev/null and it still works just to make sure that's not causing the kubernetes discrepancy)

## Possible Solution

Maybe adding a log entry when there is an error from the code endpoint.

## Steps to Reproduce (for bugs)

This is my kubernetes setup (just the deployment)
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: ***
  name: ***
  namespace: ***
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: ***
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: ***
    spec:
      containers:
      - args:
        - --provider=oidc
        - --email-domain=*
        - --upstream=file:///dev/null
        - --http-address=0.0.0.0:4180
        - --skip-provider-button=true
        - --oidc-issuer-url=https://***/
        - --login-url=https://***/
        - --extra-jwt-issuers="https://login.selfstudy.com/=https://***/v1/api,https://***/=https://***/v1/api"
        - --scope="openid email profile"
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          value:***
        - name: OAUTH2_PROXY_CLIENT_SECRET
          value:***
        - name: OAUTH2_PROXY_COOKIE_SECRET
          value:***
        image: *** tried various different builds ***
        imagePullPolicy: Always
        name: ***
        ports:
        - containerPort: 4180
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
```
1.   This config acts the same way during login as the local one.
2.   Then the final call to /oauth2/callback fails and the code request does not contain an id_token.
3.   No error is logged other than:
```
2019-10-16T00:56:08.779205524Z [2019/10/16 00:56:08] [oauthproxy.go:634] Error redeeming code during OAuth2 callback: unable to update session: token response did not contain an id_token 
 E 
2019-10-16T00:56:08.779404300Z 10.36.6.1 - - [2019/10/16 00:56:08] iars360v2--codefresh-container-auth.selfstudy.ai GET - "/oauth2/callback?code=Nifzz1z2opL8S_y7&state=b97a10db8f4cdcba825df2afdd9a2e61%3A%2Ffavicon.ico" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36" 500 331 0.107
 E 
2019-10-16T06:27:50.645662351Z [2019/10/16 06:27:50] [oauthproxy.go:748] Error loading cookied session: Cookie "_oauth2_proxy" not present
 E 
2019-10-16T06:27:50.645736306Z 10.36.6.1 - - [2019/10/16 06:27:50] iars360v2--codefresh-container-auth.selfstudy.ai GET - "/oauth2/auth" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:65.0) Gecko/20100101 Firefox/65.0" 401 21 0.001
 E 
2019-10-16T06:27:50.748425443Z 10.240.0.15 - - [2019/10/16 06:27:50] iars360v2--codefresh-container-auth.selfstudy.ai GET - "/oauth2/start?rd=%2F" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:65.0) Gecko/20100101 Firefox/65.0" 302 338 0.000
 E 
```
4.  

## Context

I am using auth0 with oidc and I switched the auth0 client to be oidc compliant. This works fine in the local proxy setup.

## Your Environment

GKE cluster in deployment
Mac OS in local

- Version used:
Tried various versions. Created a fork and built latest, used the master tag and so on. They all seem the act identical. I am suspecting that there is a more descriptive error hidden inside of the redeem call. I will try to add some logging, but I have not done a lot of go work.
