### ISSUE TITLE
Redirect issues with Envoy

### ISSUE THREAD

**Issue by Just-Insane** [pusher/oauth2_proxy#350]
When setting up Oauth2_Proxy with Envoy via Istio, the direction to the IDP works (keycloak), and I can get authenticated (as shown in the Oauth2_Proxy logs), however, I am redirected to the base domain of the OAuth proxy, not the URL of the service that originally entered the flow.

## Expected Behavior

After authenticating with Keycloak and being redirected, the user should be sent to the service they were originally trying to access. For example:

1. The user goes to `https://demo.corp.domain.com`
2. User is redirected to `https://oauth.corp.domain.com/oauth2/start?rd=https://demo.corp.domain.com`
3. User is redirected to `https://auth.domain.com` to sign in
4. User is redirected to `https://oauth.corp.domain.com/oauth2/callback`
5. User is redirected to `https://demo.corp.domain.com`

## Current Behavior

1. The user goes to `https://demo.corp.domain.com`
2. User is redirected to `https://oauth.corp.domain.com/oauth2/start?rd=https://demo.corp.domain.com`
3. User is redirected to `https://auth.domain.com` to sign in
4. User is redirected to `https://oauth.corp.domain.com/oauth2/callback`
5. User is redirected to `https://oauth.corp.domain.com`

## Possible Solution

Provide documentation about configuring the Envoy ext_authz feature.

## Steps to Reproduce (for bugs)

1. Kubernetes cluster running Istio 1.3 with an ingress-gateway setup
2. Keycloak setup and client created
3. Deploy oauth2_proxy with the following config

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: oauth2-proxy
  template:
    metadata:
      labels:
        k8s-app: oauth2-proxy
    spec:
      containers:
        - args:
            - --provider=keycloak
            - --email-domain=corp.domain.com
            - --email-domain=domain.com
            - --pass-basic-auth=false
            - --pass-access-token=true
            - --set-authorization-header=true
            - --pass-authorization-header=true
            - --http-address=0.0.0.0:4180
            - --login-url=https://auth.domain.com/auth/realms/realm/protocol/openid-connect/auth
            - --redeem-url=https://auth.domain.com/auth/realms/realm/protocol/openid-connect/token
            - --validate-url=https://auth.domain.com/auth/realms/realm/protocol/openid-connect/userinfo
            - --cookie-expire=4h0m0s
            - --whitelist-domain=".corp.domain.com",".domain.com"
            - --cookie-domain=.corp.domain.com
          env:
            - name: OAUTH2_PROXY_CLIENT_ID
              value: rancher-demo
            - name: OAUTH2_PROXY_CLIENT_SECRET
              value: <secret>
            # docker run -ti --rm python:3-alpine python -c 'import secrets,base64; print(base64.b64encode(base64.b64encode(secrets.token_bytes(16))));'
            - name: OAUTH2_PROXY_COOKIE_SECRET
              value: <secret>
            - name: OAUTH2_PROXY_COOKIE_DOMAIN
              value: .corp.domain.com
          image: quay.io/pusher/oauth2_proxy:v4.1.0
          imagePullPolicy: Always
          name: oauth2-proxy
          ports:
            - containerPort: 4180
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauthproxy-service
  namespace: default
spec:
  ports:
    - name: http
      port: 4180
      protocol: TCP
      targetPort: 4180
  selector:
    k8s-app: oauth2-proxy
```

4. Deploy an envoy filter with the following config:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: authn-filter
spec:
  workloadSelector:
    labels:
      app: istio-ingressgateway
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          portNumber: 443
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.lua
          config:
            inlineCode: |
              base_host = string.upper("corp.domain.com")
              a, oauth_host = string.match("corp.domain.com", '(corp.*%.)(.*%..*)')
              oauth_host = "oauth." .. oauth_host

              function starts_with(str, start)
                return str:sub(1, #start) == start
              end

              function ignore_request (request_handle)
                local host = string.upper(request_handle:headers():get(":authority"))
                local path = request_handle:headers():get(":path")
                -- we skip un-protected hosts or 'well-known' paths (used for e.g. acme)
                i, j = string.find(host, base_host, 0, true)
                if i == nil or starts_with(path, '/.well-known/') then
                  return true
                end

                -- request_handle:logWarn("Host protected")
                return false
              end

              function login (request_handle)
                local request_url = "https://"..request_handle:headers():get(":authority")..request_handle:headers():get(":path")
                local redirect_url = "https://"..oauth_host.."/oauth2/start?rd="..request_url
                headers = {
                    [":status"] = 302,
                    ["location"] = redirect_url
                }
                request_handle:respond(headers, "")
              end

              function envoy_on_request(request_handle)
                if ignore_request(request_handle) then
                  return
                end

                cookie = request_handle:headers():get("Cookie")
                if cookie == nil then
                  -- request_handle:logWarn("login")
                  login(request_handle)
                  return
                end
                -- request_handle:logWarn("validating token against /ouath2/auth")
                local headers, body = request_handle:httpCall(
                    "outbound|443||"..oauth_host,
                    {
                      [":method"] = "GET",
                      [":path"] = "/oauth2/auth",
                      [":authority"] = oauth_host,
                      ["Cookie"] = cookie
                    },
                    nil,
                    5000)
                local status
                for header, value in pairs(headers) do
                  if header == ":status" then
                      status = value
                  end
                end

                -- request_handle:logWarn("token validation status:"..status)
                if status ~= "202" then
                  -- request_handle:logWarn("Not validated")
                  login(request_handle)
                  return
                end
                if status ~= "404" then
                  local request_url = "https://"..request_handle:headers():get(":authority")..request_handle:headers():get(":path")
                  local redirect_url = "https://"..oauth_host.."/oauth2/start?rd="..request_url
                  headers = {
                    [":status"] = 302,
                    ["location"] = redirect_url
                  }
                  request_handle:respond(headers, "")
                end
              end

```
- From https://github.com/istio/istio/issues/14969#issuecomment-573445692

5. Deploy Destination Rule and Service Entry

Destination Rule:
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: oauth-corp-domain-com
spec:
  host: oauth.corp.domain.com
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
      - port:
          number: 443
        tls:
          mode: SIMPLE  # initiates HTTPS when accessing oauth2.agilicus.ca
          sni: oauth.corp.domain.com

```

Service Entry:
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: oauth2
spec:
  hosts:
    - oauth.corp.domain.com   # This gives us a cluster for the lua filter to target
  ports:
    - number: 443
      name: https-for-tls
      protocol: HTTPS
  resolution: DNS

```

- From https://github.com/istio/istio/issues/14969#issuecomment-532658655

6. Deploy a demo application (such as Istio's bookinfo demo.

7. Deploy an authentication policy for your demo app to ensure JWT authentication

```
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: ingress-auth-policy
spec:
  targets:
  - name: rancher-demo
  origins:
  - jwt:
      issuer: "https://auth.justin-tech.com/auth/realms/Justin-Tech"
      jwksUri: "https://auth.justin-tech.com/auth/realms/Justin-Tech/protocol/openid-connect/certs"
  principalBinding: USE_ORIGIN
```

8. Try to access your demo application, and you will not be redirected to the demo application after successful authentication

## Context

Trying to have applications behind an Instio ingress gateway secured by OIDC. Since Istio currently only verifies that the JWT token is valid, you need to use another application that can go through the OIDC auth flow to get a token. Most online solutions are using Envoy Filters, and there is not much documentation about using the Envoy ext_authz feature available. If this is supported, it may be easier than using a filter.

Additionally, since there are many subdomains, it would be nice to have the Oauth2_Proxy at its own subdomain. (Similar to https://github.com/pusher/oauth2_proxy/issues/109 and https://github.com/pusher/oauth2_proxy/issues/125, however, I believe I have followed all of the suggestions from those threads)

## Your Environment

Istio 1.3 (via Rancher)
Kubernetes 1.16.3 launched by Rancher
Ouath2_Proxy 1.4.0

- Version used: 1.4.0

**Comment by Just-Insane** [comment]
This log `127.0.0.1 - - [2020/01/13 02:27:32] oauth.corp.domain.com GET - "/oauth2/start?rd=https://rancher-demo.corp.domain.com/" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:72.0) Gecko/20100101 Firefox/72.0" 302 317 0.000` at the start of the oauth flow shows the proxy getting a request with the correct redirect location, however by the time this request gets to Keycloak, the redirect_url becomes oauth.corp.domain.com, which is incorrect.

**Comment by tsraza** [comment]
@Just-Insane There are a couple things you should try.  First upgrade to the latest version of oauth2_proxy if you can (v4.1.0)

1. set the `-upstream` flag in the oauth2_proxy.  If using `envoy.ext_authz`, then it should be `-upstream=static://200`.  Otherwise set it to the service url.
2. add the `ext_authz` filter to your envoy config.  I don't know offhand how to do it via Istio, but the raw config should explicitly allow for certain headers such as

```yaml
          http_filters:
          - name: envoy.ext_authz
            config:
              failure_mode_allow: false
              http_service:
                server_uri:
                  uri: http://oauth2_proxy_service:4180
                  cluster: oauth2_proxy
                  timeout: 1.25s
                authorization_request:
                  allowed_headers:
                    patterns:
                    - exact: cookie
                authorization_response:
                  allowed_upstream_headers:
                    patterns:
                    - prefix: x-forwarded
                    - prefix: x-auth-request
```

**Comment by Just-Insane** [comment]
I have actually gotten this working, I plan on writing up a blog post/PR for docs at some point.

One thing I can't get working is passing a JWT to Istio from a cookie, but that may be because the cookie containing the JWT is encrypted using the client secret.

This is my current envoy filter:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: authn-filter
spec:
  workloadLabels:
    istio: ingressgateway
  filters:
  - filterConfig:
      http_service:
        server_uri:
          uri: http://oauthproxy-service.default.svc.cluster.local
          cluster: outbound|4180||oauthproxy-service.default.svc.cluster.local
          timeout: 0.5s
        authorizationRequest:
          allowedHeaders:
            patterns:
            - exact: "cookie"
            - exact: "x-forwarded-access-token"
            - exact: "x-forwarded-user"
            - exact: "x-forwarded-email"
            - exact: "authorization"
            - exact: "x-forwarded-proto"
            - exact: "proxy-authorization"
            - exact: "user-agent"
            - exact: "x-forwarded-host"
            - exact: "from"
            - exact: "x-forwarded-for"
            - exact: "accept"
        authorizationResponse:
          allowedClientHeaders:
            patterns:
            - exact: "location"
            - exact: "proxy-authenticate"
            - exact: "set-cookie"
            - exact: "authorization"
            - exact: "www-authenticate"
          allowedUpstreamHeaders:
            patterns:
            - exact: "location"
            - exact: "proxy-authenticate"
            - exact: "set-cookie"
            - exact: "authorization"
            - exact: "www-authenticate"
    filterName: envoy.ext_authz
    filterType: HTTP
    listenerMatch:
      portNumber: 443
      listenerType: GATEWAY
``` 

Here is the (not working) filter to pass the JWT to Istio.

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: istio-sso-filter-live
spec:
  workloadLabels:
    keycloak_sso_filter: "live"
  filters:
  - filterConfig:
      inlineCode: |
        function stringSplit(inputstr, sep)
          if sep == nil then
            sep = "%s"
          end
          local t={}
          for str in string.gmatch(inputstr, "([^"..sep.."]+)") do
            print ("str = "..str)
            table.insert(t, str)
          end
          return t
        end
        function envoy_on_request(handle)
          headers = handle:headers()
          streamInfo = handle:streamInfo()
          connection = handle:connection()
          dynamicMetadata = streamInfo:dynamicMetadata()
          dynamicMetadata:set("request_headers", "request_authority", headers:get(":authority"))
          dynamicMetadata:set("request_headers", "request_path", headers:get(":path"))
 
          proto = "http"
          if connection:ssl() ~= nil then
            proto = "https"
          else
            forwarded_proto = headers:get("x-forwarded-proto")
            if forwarded_proto ~= nil then
              proto = forwarded_proto
            end
          end
          dynamicMetadata:set("request_headers", "proto", proto)
 
          cookieString = headers:get("cookie")
          print (cookieString)
          if cookieString ~= nil then
            splitCookieString = stringSplit(cookieString, ";")
 
            jwt = nil
            for i, cookieItem in ipairs(splitCookieString) do
              print ("cookieItem = "..cookieItem)
              if string.find(cookieItem, "k8_sso") ~= nil then
                jwt = string.gsub(cookieItem, "k8_sso=", "")
                print ("1 jwt = "..jwt)
              end
            end
 
            if jwt ~= nil then
              print ("2 jwt = "..jwt)
              jwt = string.gsub(jwt, "%s+", "")
              print ("3 jwt = "..jwt)
              auth = string.gsub(jwt, "^ ", "")
              headers:replace("x-sso-auth", auth)
              print ("x-sso-auth = "..auth)
            end
          end
        end
    filterName: envoy.lua
    filterType: HTTP
    listenerMatch:
      listenerType: ANY
```
and the policy:

```yaml
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: ingress-auth-policy
spec:
  targets:
  - name: rancher-demo
  origins:
  - jwt:
      issuer: "https://auth.justin-tech.com/auth/realms/Justin-Tech"
      jwksUri: "https://auth.justin-tech.com/auth/realms/Justin-Tech/protocol/openid-connect/certs"
      jwtHeaders:
      - x-sso-auth
  principalBinding: USE_ORIGIN
```

and here is the working OAuth2_Proxy config:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: oauth2-proxy
  template:
    metadata:
      labels:
        k8s-app: oauth2-proxy
    spec:
      containers:
        - args:
            - --provider=keycloak
            - --email-domain=corp.justin-tech.com
            - --email-domain=justin-tech.com
            - --pass-basic-auth=false
            - --pass-access-token=true
            - --pass-authorization-header=true
            - --http-address=0.0.0.0:4180
            - --login-url=https://auth.justin-tech.com/auth/realms/Justin-Tech/protocol/openid-connect/auth
            - --redeem-url=https://auth.justin-tech.com/auth/realms/Justin-Tech/protocol/openid-connect/token
            - --validate-url=https://auth.justin-tech.com/auth/realms/Justin-Tech/protocol/openid-connect/userinfo
            - --cookie-expire=4h0m0s
            - --whitelist-domain=".corp.justin-tech.com"
            - --cookie-domain=.justin-tech.com
            - --standard-logging=true
            - --auth-logging=true
            - --request-logging=true
            - --skip-provider-button=true
            - --upstream=static://
          env:
            - name: OAUTH2_PROXY_CLIENT_ID
              value: rancher-demo
            - name: OAUTH2_PROXY_CLIENT_SECRET
              value: 
            # python -c 'import os,base64; print base64.urlsafe_b64encode(os.urandom(32))'
            - name: OAUTH2_PROXY_COOKIE_SECRET
              value: 
            - name: OAUTH2_PROXY_COOKIE_DOMAIN
              value: .justin-tech.com
          image: quay.io/pusher/oauth2_proxy:v4.1.0
          imagePullPolicy: Always
          name: oauth2-proxy
          ports:
            - containerPort: 4180
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauthproxy-service
  namespace: default
spec:
  ports:
    - name: http
      port: 4180
      protocol: TCP
      targetPort: 4180
  selector:
    k8s-app: oauth2-proxy
```
