### ISSUE TITLE
Redirect to '/' instead of rd URL

### ISSUE THREAD

**Issue by ahoeing** [pusher/oauth2_proxy#378]
I have issues with the redirect location when using OAuth Proxy with Kubernetes and nginx Ingress.

My Configuration:
```
    spec:
      containers:
        - args:
            - --provider=oidc
            - --redirect-url=https://proxy.intern.my.domain.cloud/oauth2/callback
            - --oidc-issuer-url=https://login.intern.my.domain.cloud/auth/realms/myrealm
           # - --cookie-secure=false
            - --upstream=file:///dev/null
            - --http-address=0.0.0.0:4180
            - --email-domain=*
            - --insecure-oidc-allow-unverified-email=true
            - --whitelist-domain=.intern.my.domain.cloud
            - --cookie-domain=.intern.my.domain.cloud
          # Register a new application
          # https://github.com/settings/applications/new
          env:
            - name: OAUTH2_PROXY_CLIENT_ID
              value: clientid
            - name: OAUTH2_PROXY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: clientSecret
            - name: OAUTH2_PROXY_COOKIE_SECRET
              value: <secret>
          image: quay.io/pusher/oauth2_proxy:latest
          imagePullPolicy: Always
          name: oauth2-proxy
          ports:
            - containerPort: 4180
              protocol: TCP
```

The proxy has an ingress at `proxy.intern.my.domain.cloud`.

The ingress of the service (https://myservice.intern.my.domain.cloud) I want to protect:
```
    nginx.ingress.kubernetes.io/auth-url: "https://proxy.intern.my.domain.cloud/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://proxy.intern.my.domain.cloud/oauth2/start?rd=https://$host$request_uri"
```

After login, the redirect from `https://proxy.intern.my.domain.cloud/oauth2/callback` points to `/` instead to the URL from my service. So I get a 404.

The request URL when invoking my service seems to be correct:
`https://proxy.intern.my.domain.cloud/oauth2/start?rd=rd=https://myservice.intern.my.domain.cloud/`

When I invoke `https://myservice.intern.my.domain.cloud/` after the 404, everything works fine and I am authenticated.

What am I missing here?

**Comment by tlawrie** [comment]
Hey @ahoeing not sure if this is the right direction, however we hit similar issues and what helped us was the declaration in the ingress definition that points to this...

We added `rd=$request_uri` rather than `rd=$uri` to the `ingress.kubernetes.io/auth-signin` annotation.

Also in the above, it seems that there might be two `rd=` in `https://proxy.intern.my.domain.cloud/oauth2/start?rd=rd=https://myservice.intern.my.domain.cloud/`

Which would then mean

```
nginx.ingress.kubernetes.io/auth-signin: https://$host/oauth2/sign_in?rd=$request_uri
nginx.ingress.kubernetes.io/auth-url: https://proxy.intern.my.domain.cloud/oauth2/auth
```

or something similar.

**Comment by ahoeing** [comment]
@tlawrie Thanks, I found my issue. I messed up the re-deployment of the Ingress.

**Comment by unfor19** [comment]
@ahoeing any chance that you remember what was messed up? I have the **exact** same issue

**Comment by benni336** [comment]
I spend some hours on the exact same problem, because I took code from here:
[contrib/local-environment/nginx.conf](https://github.com/oauth2-proxy/oauth2-proxy/blob/master/contrib/local-environment/nginx.conf)) . Hope I will save some time for the next one. ;)

**Comment by JoelSpeed** [comment]
@benni336 To use the redirect you should also allow the domain that you are redirecting to, using the `whitelist-domain` flag. Note the logs should now report an error when an invalid redirect is passed, I suspect the reason it wasn't working for you is because of the lack of that flag or a misconfiguration of the flag

**Comment by c-dev-acc1** [comment]
I have exactly problem. After login, instead of redirect to `https://app.example.com/myapp`, it redirect me to `https://auth.example.com/`. Do I miss somethings?

I have whitelist_domains in my my config file:

```
http_address = "0.0.0.0:4180"
https_address = ":443"
upstreams = [
  "file:///dev/null"
]
email_domains = "*"
provider = "github"
client_id = "myid"
client_secret = "mysecret"
scope = "user:email read:user read:org"
cookie_secret = "aVYba9oi7Aqnl7QcbeMtLOFtQETwHDl5NTfVbI73d0E="
cookie-domains = "*.example.com"
whitelist_domains = "*.example.com"
```

This is my app ingress:
```
apiVersion: networking.k8s.io/v1
kind: Ingress 
metadata:  
  name: myapp
  annotations:
    nginx.ingress.kubernetes.io/auth-response-headers: Authorization
    nginx.ingress.kubernetes.io/auth-url: "https://auth.example.com/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://auth.example.com/oauth2/start?rd=$scheme://$host$request_uri"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      auth_request_set $name_upstream_1 $upstream_cookie__oauth2_proxy_1;

      access_by_lua_block {
        if ngx.var.name_upstream_1 ~= "" then
          ngx.header["Set-Cookie"] = "_oauth2_proxy_1=" .. ngx.var.name_upstream_1 .. ngx.var.auth_cookie:match("(; .*)")
        end
      }
spec:
  ingressClassName: nginx
  rules:
  - host: app.example.com
    http:
      paths:
      - path: /myapp
        pathType: Exact   
        backend:
          service:
            name: myapp
            port:   
              number: 80
  tls:
  - hosts:
      - app.example.com
    secretName: tls-example.com
```

And oauth2-proxy ingress:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oauth2-proxy
spec:
  ingressClassName: nginx
  rules:
  - host: auth.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: oauth2-proxy
            port:
              number: 4180
  tls:
  - hosts:
    - auth.example.com
    secretName: tls-example.com
```
