### ISSUE TITLE
[DOCKER] extra_hosts ignored

### ISSUE THREAD

**Issue by luketainton** [pusher/oauth2_proxy#387]
When specifying extra_hosts (to modify the container's hosts file), these are ignored.

## Expected Behavior
When getting the openid-configuration from the Keycloak URL, it should be using the specified IP address to get to the login server, not the publicly resolvable IP.

## Current Behavior
It is still using the public IP, and due to firewall configuration this isn't working.

## Steps to Reproduce (for bugs)
Run the service in Docker using the following docker-compose.yml snippet:
```
web:
    image: quay.io/pusher/oauth2_proxy:v5.0.0
    restart: unless-stopped
    extra_hosts:
      - "login.citygate.io:<INTERNAL_IP>"
    expose:
      - 4180
    entrypoint:
      - /bin/oauth2_proxy
      - --provider=oidc
      - --client-id=nodered
      - --client-secret=<REDACTED>
      - --oidc-issuer-url=https://login.citygate.io/auth/realms/master
      - --keycloak-group=/NodeRED/Users
      - --email-domain="citygate.io"
      - --upstream="http://app:1880/"
      - --cookie-secret="<REDACTED>"
      - --cookie-secure=true
      - --reverse-proxy=true
      - --http-address="0.0.0.0:4180"
    links:
      - app
    depends_on:
      - app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nodered.rule=Host(`nodered.citygate.io`)"
      - "traefik.http.routers.nodered.entrypoints=https"
      - "traefik.http.routers.nodered.tls=true"
      - "traefik.http.routers.nodered.tls.certResolver=le"
      - "traefik.http.services.nodered.loadbalancer.server.port=4180"
      - "traefik.http.services.nodered.loadbalancer.server.scheme=http"
```

## Context
The OAuth2 proxy cannot get the OpenID Configuration which means users cannot authenticate.

## Your Environment
- Version used: 5.0.0
- OS: Linux (in Docker)
