### ISSUE TITLE
Error loading cookied session: Cookie "_oauth2_proxy" not present

### ISSUE THREAD

**Issue by zanghao2** [pusher/oauth2_proxy#428]
I use dex and oauth_proxy to authenticate and authorize k8s applications. When I login my username and password page jumped and get the information server can not be reached.
The log infor of oath2_proxy is Error loading cookied session: Cookie "_oauth2_proxy" not present.
## Expected Behavior
I can access the service normally after logging in.

## Current Behavior
The server can not be reached.

## Possible Solution
I want to know if I should add other configuration in nginx ingress or if there is something wrong with my configuration.

## Steps to Reproduce (for bugs)

1.  I deploy a deployment and a service.
2.  I use helm to deploy oauth2_proxy and the value as follows:
```
config:
  clientID: "oauth_proxy"
  clientSecret: "oauth_proxy"
  cookieSecret: "CdZulwsl18VvCA7G0kZaSw=="
  configFile: |-
    email_domains = [ "*" ]
    upstreams = [ "http://serviceName:80" ]

image:
  repository: "quay.io/pusher/oauth2_proxy"
  tag: "latest"
  pullPolicy: "IfNotPresent"
extraArgs:
  upstream: "http://qlkube:80"
  provider-display-name: "dex"
  cookie-secure: false
  provider: oidc
  oidc-issuer-url: https://dex-ver.mytest.com.cn
  set-authorization-header: true
  whitelist-domain: ".mytest.com.cn"
  cookie-domain: ".mytest.com.cn"
  cookie-httponly: true
  cookie-name: "_oauth2_proxy"
  cookie-samesite: "none"
  skip-provider-button: true
  scope: "openid groups profile email"
  exclude-logging-paths: "/ping"
  redirect-url: "http://oauth-proxy.mytest.com.cn/oauth2/callback"
  reverse-proxy: true
  pass-authorization-header: true
  pass-access-token: true
  pass-basic-auth: true
  pass-host-header: true
  pass-user-headers: true
  session-store-type: "cookie"
  set-xauthrequest: true
  set-authorization-header: true
  skip-auth-preflight: false
``` 
and the ingress is:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx-external
  labels:
    app: oauth2-proxy
    chart: oauth2-proxy-2.1.1
    heritage: Tiller
    release: test
  name: test-oauth2-proxy
spec:
  rules:
  - host: oauth-proxy.mytest.com.cn
    http:
      paths:
      - backend:
          serviceName: test-oauth2-proxy
          servicePort: 80
        path: /
```
3.  dex service is normal.
4.  I used chrome browser to visit oauth-proxy.mytest.com.cn and jumped to dex normally. Then, I entered my username and password and clicked login. The service was unreachable。

## Your Environment

- Version used:
oauth2_proxy: latest
