### ISSUE TITLE
--whitelist-domain doesn't respect protocol on redirect

### ISSUE THREAD

**Issue by agusl88** [pusher/oauth2_proxy#54]
I'm using oauth2_proxy with AWS Cognito. Previously i was using bitly/OAuth2_Proxy and multiple oauth2_proxy pods in k8s to protect all the internal services, now i'm trying to replace those multiples pods with the `--whitelist-domain` setting available in v3.1.0 of this fork. 

The problem i'm having is that oauth_proxy is setting HTTP as protocol on the redirect URL, ignoring the callbacks defined in Cognito, which all have HTTPS as protocol

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: oauth2-proxy
  template:
    metadata:
      labels:
        k8s-app: oauth2-proxy
    spec:
      containers:
      - args:
        - --provider=oidc
        - --email-domain=*
        - --upstream=file:///dev/null
        - --http-address=0.0.0.0:4180
        - --scope=openid
        - --cookie-secure=false
        - --oidc-issuer-url=https://cognito-idp.us-east-1.amazonaws.com/POOL_ID
        - --whitelist-domain=.mydomain.com
        - --login-url=https://oauth.mydomain.com/oauth2/authorize
        - --profile-url=https://oauth.mydomain.com/oauth2/userInfo
        - --redeem-url=https://oauth.mydomain.com/oauth2/token
        env:
           .....
        image: quay.io/pusher/oauth2_proxy:v3.1.0
        imagePullPolicy: Always
        name: oauth2-proxy
        ports:
        - containerPort: 4180
          protocol: TCP
```

![captura de pantalla 2019-02-11 a la s 11 52 36](https://user-images.githubusercontent.com/4117991/52571772-0673ca80-2df5-11e9-9c7b-66dd26a6d5ca.png)
![captura de pantalla 2019-02-11 a la s 11 55 20](https://user-images.githubusercontent.com/4117991/52571773-0673ca80-2df5-11e9-815e-612a05833472.png)

- Version used:

3.1.0
