### ISSUE TITLE
oauth2_proxy configured with oidc provider quietly does not sign in

### ISSUE THREAD

**Issue by Ghazgkull** [pusher/oauth2_proxy#64]
## Context
I am trying to use oauth2_proxy to add Okta authentication to a browser-based application (Kibana).

Following all the information I could gather from the README, Issues, and PRs, I've done my best to configure oauth2_proxy for this purpose. I've gotten to the point that attempts to access my application are properly intercepted by oauth2_proxy and I see the sign-in page. But at this point clicking the button to sign in doesn't kick off the authentication process and I don't know why.

## Expected Behavior

I would expect to see some information in the oauth2_proxy console output that would help me debug the problem. Some information that would either positively or negatively confirm that my configuration is correct, that my OIDC provider is providing the info that oauth2_proxy needs, and some trace information about the requests oauth2_proxy is seeing both in terms of proxying and in terms of actions initiated from its own UI (the sign-in page).

## Current Behavior

I see two pieces of information logged: a message about a missing cookie and a generic message dumping the routes that have been hit:

```
2019/02/14 18:59:12 oauthproxy.go:796: 172.16.4.250:51816 Cookie "_oauth2_proxy_my_app" not present
172.16.4.250 - - [14/Feb/2019:18:59:12 +0000] my.subdomains.platforms.my_company.com GET - "/" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.81 Safari/537.36" 403 2523 0.000
2019/02/14 18:59:14 oauthproxy.go:796: 172.16.4.250:51816 Cookie "_oauth2_proxy_my_app" not present
172.16.4.250 - - [14/Feb/2019:18:59:14 +0000] my.subdomains.platforms.my_company.com GET - "/oauth2/start?rd=%2F" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.81 Safari/537.36" 403 2542 0.000
```

## Possible Solution

A couple thoughts come to mind:
1. It would be great if there was a way to enable verbose logging with oauth2_proxy dumping out a lot more information about how it's been configured and what it's attempting/failing to do at runtime.
2. If there are any causes of this particular case ("clicking the sign-in button does nothing), it would be great to add them to a Troubleshooting section of the README. As someone new to oauth2_proxy, this problem feels like a dead end. 

## Steps to Reproduce (for bugs)

1. I am running oauth2_proxy in a container in Kubernetes, using the helm chart published at `stable/oauth2_proxy`
2. At my ingress, I route traffic on the route "/logs" to the oauth2_proxy, so I set a proxy-prefix of "/logs/oauth2". (I'm putting this proxy in front of Kibana for an EFK stack, hence "/logs".)
3. Here's the values.yaml file I use to configure the proxy:
```
# Oauth client configuration specifics
config:
  # OAuth client ID
  clientID: "my.okta.client.id"
  # OAuth client secret
  clientSecret: "my.okta.client.secret"
  # Create a new secret with the following command
  # python -c 'import os,base64; print base64.b64encode(os.urandom(16))'
  cookieSecret: "G06IvASrTGSPWUm8l9EEKg=="
  # Custom configuration file: oauth2_proxy.cfg
  # configFile: |-
  #   pass_basic_auth = false
  #   pass_access_token = true
  configFile: ""

service:
  port: 80

extraArgs:
  email-domain: "my-company.com"
  upstream: "http://my-service"
  provider: "oidc"
  oidc-issuer-url: "https://my-company.okta.com"
  cookie-name: "_oauth2_proxy_my_app"
  cookie-secure: "false"
  cookie-httponly: "false"
  proxy-prefix: "/logs/oauth2"
```
  * Note that the `config` section gets loaded into Kubernetes secrets which ultimately are fed to the binary via environment variables OAUTH2_PROXY_CLIENT_ID, OAUTH2_PROXY_CLIENT_SECRET, and OAUTH2_PROXY_COOKIE_SECRET.
  * Note that the `extraArgs` section gets turned directly into arguments passed to oauth2_proxy as `--key=value` pairs.

## Your Environment

Running oauth2_proxy in a kubernetes pod behind an Istio ingress on AWS EKS.

- Version used:

3.1.0
docker image: https://quay.io/repository/pusher/oauth2_proxy?tag=v3.1.0
