### ISSUE TITLE
--authenticated-emails-file fully ignored

### ISSUE THREAD

**Issue by dannyyy** [pusher/oauth2_proxy#73]
I set up `oauth2-proxy` through the stable Helm chart `helm install stable/oauth2-proxy`.
Through the `answer.yaml` I did the following overrides from the default:
```
---
  config: 
    clientID: "<id>.apps.googleusercontent.com"
    clientSecret: "<secret>"
    cookieSecret: "<cookie-secret>"
  extraArgs: 
    provider: "google"
  authenticatedEmailsFile:
    enabled: true
    restricted_access: |-
      user1@gmail.com

```
The pod is spinned up with the following params:
```
spec:
  containers:
  - args:
    - --email-domain=*
    - --http-address=0.0.0.0:4180
    - --provider=google
    - --upstream=file:///dev/null
    - --authenticated-emails-file=/etc/oauth2-proxy/authenticated-emails-list
``` 

## Expected Behavior

After calling a protected domain I should be forwarded to the identity provider and after a successful authentication process redirected to my application.
`oauth2-proxy` should consider which email addresses are whitelisted with the `--authenticated-emails-file` flag

## Current Behavior

`oauth2-proxy` do not respect the settings inside `--authenticated-emails-file`. Every single email address which has been authenticated through google is valid and grants access to the application.

## Possible Solution

I guess it's a misconfiguration from my side.

## Steps to Reproduce (for bugs)

1.  Install the stable `oauth2-proxy` Helm chart with the parameters listed above
2. Create a simple web deployment
3.  Expose the web application through two ingress objects
```
metadata:
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-signin: https://$host/oauth2/start?rd=$request_uri
    nginx.ingress.kubernetes.io/auth-url: https://$host/oauth2/auth
spec:
  rules:
  - host: grafana.mydomain.tld
    http:
      paths:
      - backend:
          serviceName: prometheus-grafana
          servicePort: 80
        path: /
  tls:
  - hosts:
    - grafana.mydomain.tld
    secretName: grafana-tls-ingress
```
```
metadata:
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: grafana.mydomain.tld
    http:
      paths:
      - backend:
          serviceName: oauth2-proxy
          servicePort: 80
        path: /oauth2
  tls:
  - hosts:
    - grafana.mydomain.tld
```
4.  Open https://grafana.mydomain.tld
5. Forwarded (if not already logged in) to google. After that I get redirected back to my application

## Context

Log output from the `oauth2-proxy` pod:
```
51.xx.xx.xx - user1@gmail.com [23/Feb/2019:13:47:50 +0000] grafana.mydomain.tld GET - "/oauth2/auth" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36" 202 0 0.000
51.xx.xx.xx - user2@gmail.com [23/Feb/2019:13:47:50 +0000] grafana.mydomain.tld GET - "/oauth2/auth" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36" 202 0 0.000
51.xx.xx.xx - user3@gmail.com [23/Feb/2019:13:47:50 +0000] grafana.mydomain.tld GET - "/oauth2/auth" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36" 202 0 0.000
```

From the pod's shell:
```
cat /etc/oauth2-proxy/authenticated-emails-list
user1@gmail.com
```

## Your Environment

- Rancher `2.1.6`
- Version used:
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```
- `oauth2-proxy 0.9.1` Helm chart 
- `quay.io/pusher/oauth2_proxy:v3.1.0` image
